### ISSUE TITLE
A request

### ISSUE THREAD

**Issue by ghostiekitty** [Kylemc1413/GameplayModifiersPlus#10]
A true/false statement in the config for larger/smaller to set it so that if its true it will range randomly between 1 and the multiplier set would be nice.  So if you had 1.5 as the large multiplier it would range between 1 and 1.5 for blocks.

**Comment by Kylemc1413** [comment]
That's what the random size command is for

**Comment by ghostiekitty** [comment]
Yeah but that's random between large and small. i mean for large to only randomize between 1 and larger and small would random between 1 and smaller.

**Comment by Kylemc1413** [comment]
Smaller and larger aren't random commands, and currently I see no reason to change them to be capable of being such, I might accept a pr doing so but otherwise see no reason to mess with them
