### ISSUE TITLE
GamePlayModifiersPlus.Plugin:<AudioTimeSync>k__BackingField' (14) due to: Could not load file or assembly

### ISSUE THREAD

**Issue by MrArca9** [Kylemc1413/GameplayModifiersPlus#16]
Dealing with a strange issue. I have all the requirements installed in the mods area. The README.md and Release dependencies aren't the same but here's what i have.

### Libs:
0Harmony.dll

### Plugins:
GamePlayModifiersPlus
ChatCore
SongCore
BSML
BS_Utils
ChatCore.manifest

### Log Snippet

>[DEBUG @ 20:30:19 | IPA/LibraryLoader] Resolving library Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
[DEBUG @ 20:30:19 | IPA/LibraryLoader] Looking for file Assembly-CSharp.dll
[CRITICAL @ 20:30:19 | IPA/LibraryLoader] No library Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null found
[DEBUG @ 20:30:19 | IPA/LibraryLoader] Resolving library Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
[DEBUG @ 20:30:19 | IPA/LibraryLoader] Looking for file Assembly-CSharp.dll
[CRITICAL @ 20:30:19 | IPA/LibraryLoader] No library Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null found
[ERROR @ 20:30:19 | IPA/Loader] Could not load plugin GamePlayModifiersPlus.Plugin in GamePlayModifiersPlus.dll! System.TypeLoadException: Could not load type of field 'GamePlayModifiersPlus.Plugin:<AudioTimeSync>k__BackingField' (14) due to: Could not load file or assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. assembly:Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:<unknown type> member:(null) signature:<none>
[ERROR @ 20:30:19 | IPA/Loader]   at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x00018] in <437ba245d8404784b9fbab9b439ac908>:0 
[ERROR @ 20:30:19 | IPA/Loader]   at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic) [0x000a8] in <437ba245d8404784b9fbab9b439ac908>:0 
[ERROR @ 20:30:19 | IPA/Loader]   at System.RuntimeType.CreateInstanceSlow (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00009] in <437ba245d8404784b9fbab9b439ac908>:0 
[ERROR @ 20:30:19 | IPA/Loader]   at System.RuntimeType.CreateInstanceDefaultCtor (System.Boolean publicOnly, System.Boolean skipCheckThis, System.Boolean fillCache, System.Threading.StackCrawlMark& stackMark) [0x00027] in <437ba245d8404784b9fbab9b439ac908>:0 
[ERROR @ 20:30:19 | IPA/Loader]   at System.Activator.CreateInstance (System.Type type, System.Boolean nonPublic) [0x00020] in <437ba245d8404784b9fbab9b439ac908>:0 
[ERROR @ 20:30:19 | IPA/Loader]   at System.Activator.CreateInstance (System.Type type) [0x00000] in <437ba245d8404784b9fbab9b439ac908>:0 
[ERROR @ 20:30:19 | IPA/Loader]   at IPA.Loader.PluginManager.<LoadPluginsFromFile>g__OptionalGetPlugin|39_0[T] (System.Type t, IPA.Loader.PluginManager+<>c__DisplayClass39_0& ) [0x00023] in <12236e6af937402c97b2ad498a3206fe>:0 
[INFO @ 20:30:19 | IPA] Beat Saber
[INFO @ 20:30:19 | IPA] Running on Unity 2019.3.2f1
[INFO @ 20:30:19 | IPA] Game version 1.10.0
[INFO @ 20:30:19 | IPA] -----------------------------
[INFO @ 20:30:19 | IPA] Loading plugins from Plugins and found 5
[INFO @ 20:30:19 | IPA] -----------------------------
[INFO @ 20:30:19 | IPA] Beat Saber IPA (BSIPA): 4.0.5
[INFO @ 20:30:19 | IPA] BS_Utils (BS Utils): 1.4.10
[INFO @ 20:30:19 | IPA] BeatSaberMarkupLanguage (BeatSaberMarkupLanguage): 1.3.3
[INFO @ 20:30:19 | IPA] SongCore (SongCore): 2.9.8
[INFO @ 20:30:19 | IPA] ChatCore (ChatCore): 1.0.0-rc5
[INFO @ 20:30:19 | IPA] -----------------------------
[INFO @ 20:30:19 | IPA] -----------------------------

**Comment by Kylemc1413** [comment]
You're using an outdated version of the mod

**Comment by MrArca9** [comment]
> You're using an outdated version of the mod

Hmm, so should i build via the SLN? Or are you staging a second release past the one for 1.9.2

**Comment by MrArca9** [comment]
https://discordapp.com/channels/441805394323439646/692757693701685273/722527840712786081 - Got it, apologies!
