### ISSUE TITLE
Endless mode and RCTTS don't correctly place notes

### ISSUE THREAD

**Issue by redegg89** [Kylemc1413/GameplayModifiersPlus#21]
When the next song plays in endless or RCTTS starts, the notes and bombs are all placed on top of each other and have no collision.

Logs: [_latest.log](https://github.com/Kylemc1413/GameplayModifiersPlus/files/6448169/_latest.log)

**Comment by Kylemc1413** [comment]
Remove Chroma and wait for an update to Chroma that resolves the issue if you want to use those features

**Comment by redegg89** [comment]
Thanks! I would've never guessed Chroma was the issue
