### ISSUE TITLE
Reverse mode is left-handed as well

### ISSUE THREAD

**Issue by megalon** [Kylemc1413/GameplayModifiersPlus#8]
When playing around with reverse mode today, I noticed that it also forces left-handed mode. IE: It' s mirrored just like left-handed mode. 
Is this intentional?

**Comment by Kylemc1413** [comment]
The transformation of the blocks is intentional since if I left the blocks as is they would be red on right. blue on left. Although it may have been possible to make it not act as left handed mode I found it fitting for reverse
