### ISSUE TITLE
One Colour Does Not Register Hits

### ISSUE THREAD

**Issue by CinisSkizm** [Kylemc1413/GameplayModifiersPlus#9]
When I turn on the One Colour modifier, it no longer registers hits of any kind. A sound effect is played when my right-handed saber contacts a block, but it is not cut. The left-handed saber produces no effect.

**Comment by Kylemc1413** [comment]
This issue is fixed on source, I'm just waiting on pushing a version of Mapping Extensions that requires a version bump for this mod before releasing it, I believe turning off rumble would allow it to work properly on the public version for now, but can't remember for sure

**Comment by CinisSkizm** [comment]
Thank you, I can confirm that disabling rumble allows the One Colour modifier to work.
